var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8557abe2._.js")
R.c("server/chunks/ssr/examples_next-app_2ad52c07._.js")
R.c("server/chunks/ssr/examples_next-app_9dd66a58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fce9499a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4b5011c6._.js")
R.c("server/chunks/ssr/cce17_next_dist_72eb9095._.js")
R.c("server/chunks/ssr/examples_next-app_src_app_3424f78e._.js")
R.c("server/chunks/ssr/cce17_next_dist_client_components_builtin_global-error_e4d0a175.js")
R.c("server/chunks/ssr/[root-of-the-server]__203f37a7._.js")
R.c("server/chunks/ssr/cce17_next_dist_client_components_f5ed1518._.js")
R.c("server/chunks/ssr/cce17_next_dist_client_components_builtin_forbidden_08138e50.js")
R.c("server/chunks/ssr/cce17_next_dist_client_components_builtin_unauthorized_9fe35158.js")
R.c("server/chunks/ssr/examples_next-app__next-internal_server_app_settings_page_actions_225fc6ff.js")
R.m(6324)
module.exports=R.m(6324).exports
