import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/client-providers";
import type { Palette } from "@/components/app-theme-context";
import { Suspense } from "react";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialTheme = cookieStore.get("theme")?.value || "";
  const initialPalette = (cookieStore.get("palette")?.value || "") as Palette;
  const initialPaletteMode = cookieStore.get("palette-mode")?.value === "system" ? "system" : "custom";
  const initialSystemLight = cookieStore.get("palette-system-light")?.value || "blue";
  const initialSystemDark = cookieStore.get("palette-system-dark")?.value || "indigo";
  return (
    <html lang="en" className={initialTheme === "dark" ? "dark" : ""} suppressHydrationWarning>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased ${initialPalette ? `theme-${initialPalette}` : ""}`}>
        <Suspense fallback={null}>
          <ClientProviders
            initialPalette={initialPalette}
            initialPaletteMode={initialPaletteMode}
            initialSystemLight={initialSystemLight as Palette}
            initialSystemDark={initialSystemDark as Palette}
          >
            {children}
          </ClientProviders>
        </Suspense>
      </body>
    </html>
  );
}
